# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc7011b63e6f3b21605a4fc3c77de431ea0019decbf766ed6a59b13d6ff2723d5ef8f62f15b2e0769791b63b6646bd61f650102de2bd3f8c56303f669b8d8d5d

test:
  secret_key_base: 92b0043f5465473f3f6feee92350f10ac03e939da4b96d4311cf9734b8ab47d85c92a9efb12e7c0391c579dfe058372992d2eaeaa3484692bf119402e3b549e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
